Add information about setting global gitignore
Amsterdam/opdrachten_team_dev pull request #3
Opened 2021-10-12 08:17 UTC by moagstar

2021-10-12 08:41 UTC, kramer65 approved these changes

2021-10-12 08:52 UTC, kramer65 requested changes
Dit maakt een repo afhankelijk van een lokale setup, dus het lijkt me bij nader inzien toch geen goed idee.

2021-10-12 08:59 UTC, moagstar commented
> Dit maakt een repo afhankelijk van een lokale setup, dus het lijkt me bij nader inzien toch geen goed idee.

Op zich ben ik het ermee eens, maar ik had van @jklardie begrepen dat het werken met een globale `.gitignore` de preferente werkwijze was (zie https://github.com/Amsterdam/waarnemingen-voertuigen/pull/80). Het lijkt me goed om als team op een lijn te zitten wat dit betreft. @jklardie weet jij nog wat de afwegingen waren m.b.t. de globale gitignore?

2022-03-01 11:58 UTC, jklardie commented
Lijkt me goed om inderdaad standaard een gitignore aan projecten toe te voegen.

2022-03-01 13:19 UTC, moagstar commented
Laten we deze dus niet mergen.

2022-03-01 13:19 UTC, closed without merging